

INSERT INTO TB_TEAMKOREA
VALUES (1, 'GK', '김승규', 'KIM Seunggyu', '1990.09.30' , '사우디아라비아 알 샤바브 FC' ,'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);
INSERT INTO TB_TEAMKOREA
VALUES (12, 'GK', '송범근', 'SONG Bumkeun', '1997.10.15' , '대한민국 전북 현대 모터스', 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);
INSERT INTO TB_TEAMKOREA
VALUES (21, 'GK', '조현우', 'JO Hyeonwoo', '1991.09.25.' , '대한민국 울산 현대', 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);
INSERT INTO TB_TEAMKOREA
VALUES (2, 'DF', '윤종규', 'YOON Jonggyu', '1998.03.20' , '대한민국 FC 서울', 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);
INSERT INTO TB_TEAMKOREA
VALUES (3, 'DF', '김진수', 'KIM Jinsu', '1992.06.13' , '대한민국 전북 현대 모터스', 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);
INSERT INTO TB_TEAMKOREA
VALUES (4, 'DF', '김민재', 'KIM Minjae', '1996.11.15' , '이탈리아 SSC 나폴리', 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);
INSERT INTO TB_TEAMKOREA
VALUES (14, 'DF', '홍철', 'HONG Chul', '1990.09.17.' , '대한민국 대구 FC' ,'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);
INSERT INTO TB_TEAMKOREA
VALUES (15, 'DF', '김문환', 'KIM Moonhwan', '1995.08.01' , '대한민국 전북 현대 모터스' ,'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);
INSERT INTO TB_TEAMKOREA
VALUES (19, 'DF', '김영권', 'KIM Younggwon', '1990.02.27' , '대한민국 울산 현대', 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);
INSERT INTO TB_TEAMKOREA
VALUES (20, 'DF', '권경원', 'KWON Kyungwon', '1992.01.31' , '일본 감바 오사카' ,'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);
INSERT INTO TB_TEAMKOREA
VALUES (23, 'DF', '김태환', 'KIM Taehwan', '1989.07.24.' , '대한민국 울산 현대', 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);
INSERT INTO TB_TEAMKOREA
VALUES (24, 'DF', '조유민', 'CHO Yumin', '1996.11.17' , '대한민국 대전 하나 시티즌' ,'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);
INSERT INTO TB_TEAMKOREA
VALUES (5, 'MF', '조유민', 'JUNG Wooyoung', '1989.12.14' , '카타르 알 사드 SC', 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);
INSERT INTO TB_TEAMKOREA
VALUES (6, 'MF', '황인범', 'HWANG Inbeom', '1996.09.20' , '그리스 올림피아코스 FC', 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);
INSERT INTO TB_TEAMKOREA
VALUES (7, 'MF', '손흥민', 'SON Heungmin', '1992.07.08' , '잉글랜드 토트넘 홋스퍼 FC', 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);
INSERT INTO TB_TEAMKOREA
VALUES (8, 'MF', '백승호', 'PAIK Seungho', '1997.03.17' , '대한민국 전북 현대 모터스' ,'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);
INSERT INTO TB_TEAMKOREA
VALUES (10, 'MF', '이재성', 'LEE Jaesung', '1992.08.10' , '독일 1. FSV 마인츠 05', 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);
INSERT INTO TB_TEAMKOREA
VALUES (11, 'MF', '황희찬', 'HWANG Heechan', '1996.01.26' , '잉글랜드 울버햄튼 원더러스 FC', 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);
INSERT INTO TB_TEAMKOREA
VALUES (13, 'MF', '손준호', 'SON Junho', '1992.05.12' , '중국 산둥 타이산', 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);
INSERT INTO TB_TEAMKOREA
VALUES (17, 'MF', '나상호', 'NA Sangho', '1996.08.12' , '대한민국 FC 서울', 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);
INSERT INTO TB_TEAMKOREA
VALUES (18, 'MF', '이강인', 'LEE Kangin', '2001.02.19.' , '스페인 RCD 마요르카', 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);
INSERT INTO TB_TEAMKOREA
VALUES (22, 'MF', '권창훈', 'KWON Changhoon', '1994.06.30' , '대한민국 김천 상무 FC', 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);
INSERT INTO TB_TEAMKOREA
VALUES (25, 'MF', '정우영', 'JEONG Wooyeong', '1999.09.20' , '독일 SC 프라이부르크', 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);
INSERT INTO TB_TEAMKOREA
VALUES (26, 'MF', '송민규', 'SONG Minkyu', '1999.09.12' , '대한민국 전북 현대 모터스', 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);
INSERT INTO TB_TEAMKOREA
VALUES (9, 'FW', '조규성', 'CHO Guesung', '1998.01.25' , '대한민국 전북 현대 모터스', 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);
INSERT INTO TB_TEAMKOREA
VALUES (16, 'FW', '황의조', 'HWANG Uijo', '1992.08.28' , '그리스 올림피아코스 FC', 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);



-- TODO: login 샘플 데이터
INSERT INTO TB_ROLE VALUES(SQ_ROLE.NEXTVAL, 'ROLE_USER','N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);
-- INSERT INTO TB_ROLE(id, name) VALUES(SQ_ROLE.NEXTVAL, 'ROLE_MODERATOR');
INSERT INTO TB_ROLE VALUES(SQ_ROLE.NEXTVAL, 'ROLE_ADMIN','N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);

-- admin user 1명 최초 생성
-- id : forbob
-- password : 123456
-- email : forbob@naver.com
-- roles : ROLE_ADMIN
INSERT INTO TB_USER VALUES(SQ_USER.NEXTVAL, 'forbob@naver.com','$2a$10$TG1a5ywSrGNgf7/fFH.m0.EdTzHax8AGYNeAr8aIseF3DKyO0lDti','forbob','N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') ,NULL, NULL);
INSERT INTO TB_USER_ROLE VALUES(1, 2);

COMMIT;
